import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Instgram</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/instagram-logo.png' />
			</Head>

			{/* header */}
			<div></div>

			{/* body */}
			<div></div>
		</div>
	);
};

export default Home;
