import type { NextPage } from 'next';
import Head from 'next/head';
import Header from '../components/Header';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Instgram</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='instagram-logo-favicon.png' />
			</Head>

			{/* header */}
			<Header />

			{/* body */}
			<div className='w-full h-full dark:bg-dark-dark bg-dark-white'></div>
		</div>
	);
};

export default Home;
