import React, { useEffect, useState } from 'react';
import Header from '../components/Header';
import { faker } from '@faker-js/faker';
import { useRouter } from 'next/router';
import Head from 'next/head';
import Image from 'next/image';
import { useRecoilValue } from 'recoil';
import { userRecoil } from '../atoms/userAtom';

interface IUser {
	userId: string;
	userName: string;
	fullName: string;
	followedBy: string;
	avatar: string;
}

const SuggestedUsers = () => {
	const [usersSuggestions, setUsersSuggestions] = useState<IUser[]>([]);
	const user = useRecoilValue(userRecoil);
	const router = useRouter();

	useEffect(() => {
		if (!user) {
			// redirects if there is no user
			router.push('/signin');
		}
	}, []);

	useEffect(() => {
		const usersSuggestionsArray: any[] = [];

		for (let i = 0; i < 50; i++) {
			usersSuggestionsArray.push(createRandomUser());
		}

		setUsersSuggestions(usersSuggestionsArray);
	}, []);

	const createRandomUser = (): IUser => {
		return {
			userId: faker.datatype.uuid(),
			userName: faker.internet.userName(),
			fullName: faker.name.fullName(),
			followedBy: faker.name.firstName(),
			avatar: faker.image.avatar(),
		};
	};
	// if the user is not logged in only return the header and redirect to the signin page
	if (!user) return <Header />;

	return (
		<div>
			<Head>
				<title>Instgram | Suggested Users</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='instagram-logo-favicon.png' />
			</Head>

			<Header />

			<div className=' min-h-[93vh]  flex flex-col gap-2 items-center  pt-6 text-black dark:text-white bg-dark-white dark:bg-dark-dark '>
				<p className='text-lg font-bold pl-1 min-w-[500px] w-[40%]'>
					Suggested
				</p>

				<div className='border overflow-scroll overflow-x-hidden scrollbar-thin scrollbar-thumb-zinc-400 dark:scrollbar-thumb-zinc-500 border-gray-200 p-4 rounded-lg   h-[75vh] min-w-[500px] w-[40%] dark:border-dark-border dark:bg-dark-light bg-full-white'>
					<div className='space-y-4 '>
						{usersSuggestions?.map(
							({ userId, userName, avatar, fullName, followedBy }) => {
								return (
									<div
										className='flex items-center justify-between '
										key={userId}
									>
										<div className='flex gap-5'>
											<img
												src={avatar}
												className='w-12 h-12 rounded-full cursor-pointer'
											/>

											<div className='text-xs text-gray-500 whitespace-nowrap'>
												<p className='text-[15px] font-semibold cursor-pointer dark:text-white text-black'>
													{userName}
												</p>
												<p>{fullName}</p>
												<p>
													Followed By {followedBy}, {followedBy}
												</p>
											</div>
										</div>

										<button className='px-6 py-1 font-bold tracking-wide text-white transition-all duration-300 rounded-md hover:scale-105 hover:bg-blue-600 bg-light-blue'>
											Follow
										</button>
									</div>
								);
							}
						)}
					</div>
				</div>

				<div className='flex flex-col gap-4 mt-4'>
					<div className='flex gap-4 '>
						<p className='suggested-users-page-link'>ABOUT</p>
						<p className='suggested-users-page-link'>HELP</p>
						<p className='suggested-users-page-link'>PRESS</p>
						<p className='suggested-users-page-link'>API</p>
						<p className='suggested-users-page-link'>JOBS</p>
						<p className='suggested-users-page-link'>PRIVACY</p>
						<p className='suggested-users-page-link'>TERMS</p>
					</div>
				</div>

				<div className='flex gap-4'>
					<p className='suggested-users-page-link'>LOCATIONS</p>
					<p className='suggested-users-page-link hover:no-underline'>
						LANGUAGE
					</p>
				</div>

				<p className=' text-zinc-300 dark:text-zinc-500'>
					© {new Date().getFullYear()} Inferno Ripper
				</p>
			</div>
		</div>
	);
};

export default SuggestedUsers;
